// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMgXnjo0TbLt2WQgy2fMnWEO6GTL3BGoc',
    appId: '1:124606998862:web:b035425fd08439e512d61f',
    messagingSenderId: '124606998862',
    projectId: 'ai-app-693be',
    authDomain: 'ai-app-693be.firebaseapp.com',
    storageBucket: 'ai-app-693be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCLevjtOiiyzDlqRkxEqMOiphp68SFM24',
    appId: '1:124606998862:android:73a569176ddc459512d61f',
    messagingSenderId: '124606998862',
    projectId: 'ai-app-693be',
    storageBucket: 'ai-app-693be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxPoBSwGjOzbfMJnDByIyy-3A3ItRd0R0',
    appId: '1:124606998862:ios:f8920a3dbfdf38b912d61f',
    messagingSenderId: '124606998862',
    projectId: 'ai-app-693be',
    storageBucket: 'ai-app-693be.firebasestorage.app',
    iosBundleId: 'com.example.aiPresent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxPoBSwGjOzbfMJnDByIyy-3A3ItRd0R0',
    appId: '1:124606998862:ios:f8920a3dbfdf38b912d61f',
    messagingSenderId: '124606998862',
    projectId: 'ai-app-693be',
    storageBucket: 'ai-app-693be.firebasestorage.app',
    iosBundleId: 'com.example.aiPresent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMgXnjo0TbLt2WQgy2fMnWEO6GTL3BGoc',
    appId: '1:124606998862:web:764506427c9edf1712d61f',
    messagingSenderId: '124606998862',
    projectId: 'ai-app-693be',
    authDomain: 'ai-app-693be.firebaseapp.com',
    storageBucket: 'ai-app-693be.firebasestorage.app',
  );
}
